controller_names:
  - joint_trajectory_controller

joint_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - ur3/shoulder_pan_joint
    - ur3/shoulder_lift_joint
    - ur3/elbow_joint
    - ur3/wrist_1_joint
    - ur3/wrist_2_joint
    - ur3/wrist_3_joint
